import fs from 'node:fs';import {zipSync,strToU8} from 'fflate';
const escape=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const chapters=[['Jalan pulang','Di desa Limaraya, sore selalu berbau tanah basah. Nara pulang membawa koper kecil dan kalimat besar yang belum berani ia ucapkan: ia tidak ingin kembali ke kota. Di bawah beringin, Bima dan Sari menunggunya. Mereka membuka kembali rumah baca yang dulu mereka impikan.'],['Yang belum selesai','Bima memperbaiki rak, Sari memilah buku, dan Nara menyapu daun. Di antara buku usang, Nara menemukan cerita yang berhenti di tengah kalimat. Bima berkata bahwa akhirnya belum perlu bagus. Mereka hanya perlu tetap ada.'],['Hujan di dalam rumah','Hujan turun melewati atap. Sari mengangkat buku, Bima menggeser meja, Nara membawa ember. Mereka tidak sempat menjadi pahlawan; mereka hanya tiga orang yang enggan meninggalkan satu sama lain.'],['Boleh meminjam harapan','Di bawah lentera mereka berbagi teh dan ketakutan. Jika harapanmu habis, pinjam punyaku dulu, kata Sari. Nara kembali menulis. Rumah itu dibangun oleh orang yang saling menunggu.'],['Satu rak, banyak tangan','Anak-anak datang membawa buku. Tetangga membawa genting, kain lap dan kartu pinjam. Di bawah gambar burung hijau, Nara menulis Limaraya: tempat cerita boleh pulang.'],['Bab yang dibaca bersama','Nara membacakan cerita yang dulu terputus. Di akhir cerita mereka menemukan meja, tiga cangkir dan seseorang yang selalu menyisakan kursi. Hidupnya belum selesai diperbaiki. Namun ia tidak harus memperbaikinya sendirian.']];
const files={mimetype:strToU8('application/epub+zip'),'META-INF/container.xml':strToU8('<?xml version="1.0"?><container xmlns="urn:oasis:names:tc:opendocument:xmlns:container" version="1.0"><rootfiles><rootfile full-path="OEBPS/book.opf" media-type="application/oebps-package+xml"/></rootfiles></container>')};
files['OEBPS/book.opf']=strToU8('<?xml version="1.0"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="id">urn:flippy:limaraya</dc:identifier><dc:title>Limaraya</dc:title><dc:language>id</dc:language><meta property="dcterms:modified">2026-10-09T00:00:00Z</meta></metadata><manifest>'+chapters.map((_,i)=>'<item id="c'+i+'" href="chapter'+i+'.xhtml" media-type="application/xhtml+xml"/>').join('')+'<item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/></manifest><spine>'+chapters.map((_,i)=>'<itemref idref="c'+i+'"/>').join('')+'</spine></package>');
chapters.forEach(([title,body],i)=>{files['OEBPS/chapter'+i+'.xhtml']=strToU8('<html xmlns="http://www.w3.org/1999/xhtml" lang="id"><head><title>'+escape(title)+'</title></head><body><h1>'+escape(title)+'</h1><p>'+escape(body)+'</p>'+(i<5?'<p><a href="chapter'+(i+1)+'.xhtml">Bab berikutnya →</a></p>':'<p><em>Tamat.</em></p>')+'</body></html>')});
files['OEBPS/nav.xhtml']=strToU8('<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>Contents</title></head><body><nav epub:type="toc"><ol>'+chapters.map(([title],i)=>'<li><a href="chapter'+i+'.xhtml">'+title+'</a></li>').join('')+'</ol></nav></body></html>');
// The mimetype entry is first and uncompressed, per EPUB's OCF rules.
files.mimetype=[files.mimetype,{level:0}];fs.writeFileSync('example/limaraya.epub',zipSync(files));
const comic={};for(const [i,name] of ['cover','rain','evening'].entries())comic[String(i+1).padStart(2,'0')+'-'+name+'.jpg']=new Uint8Array(fs.readFileSync('example/story/'+name+'.jpg'));fs.writeFileSync('example/limaraya.cbz',zipSync(comic,{level:0}));
